name: classic_logger
description: It is a cross-platform classic and minimalist logger written in the Dart language.
version: 1.0.0
repository: https://github.com/myConsciousness/classic-logger.dart

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  intl: ^0.17.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
